# Generated by Django 4.1.7 on 2023-04-25 20:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("service_provider", "Service Provider"),
                            ("driver", "Driver"),
                        ],
                        default="customer",
                        max_length=21,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type", models.CharField(max_length=20)),
                ("license_plate", models.CharField(max_length=20)),
                ("license_number", models.CharField(max_length=20)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                (
                    "driver_picture",
                    models.ImageField(
                        default="driver_pictures/default.jpg",
                        upload_to="driver_pictures/",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("laundry_preferences", models.JSONField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address_line_1", models.CharField(max_length=100)),
                ("street_address_line_2", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("MA", "Massachusetts"),
                            ("NH", "New Hampshire"),
                            ("ME", "Maine"),
                            ("VT", "Vermont"),
                            ("RI", "Rhode Island"),
                            ("CT", "Connecticut"),
                            ("NY", "New York"),
                            ("NJ", "New Jersey"),
                            ("PA", "Pennsylvania"),
                            ("DE", "Delaware"),
                            ("MD", "Maryland"),
                            ("VA", "Virginia"),
                            ("WV", "West Virginia"),
                            ("NC", "North Carolina"),
                            ("SC", "South Carolina"),
                            ("GA", "Georgia"),
                            ("FL", "Florida"),
                            ("AL", "Alabama"),
                            ("MS", "Mississippi"),
                            ("TN", "Tennessee"),
                            ("KY", "Kentucky"),
                            ("OH", "Ohio"),
                            ("MI", "Michigan"),
                            ("IN", "Indiana"),
                            ("IL", "Illinois"),
                            ("WI", "Wisconsin"),
                            ("MN", "Minnesota"),
                            ("IA", "Iowa"),
                            ("MO", "Missouri"),
                            ("AR", "Arkansas"),
                            ("LA", "Louisiana"),
                            ("ND", "North Dakota"),
                            ("SD", "South Dakota"),
                            ("NE", "Nebraska"),
                            ("KS", "Kansas"),
                            ("OK", "Oklahoma"),
                            ("TX", "Texas"),
                            ("MT", "Montana"),
                            ("WY", "Wyoming"),
                            ("CO", "Colorado"),
                            ("NM", "New Mexico"),
                            ("ID", "Idaho"),
                            ("UT", "Utah"),
                            ("AZ", "Arizona"),
                            ("NV", "Nevada"),
                            ("WA", "Washington"),
                            ("OR", "Oregon"),
                            ("CA", "California"),
                            ("AK", "Alaska"),
                            ("HI", "Hawaii"),
                        ],
                        max_length=2,
                    ),
                ),
                ("zip_code", models.CharField(max_length=20)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.user"
                    ),
                ),
            ],
        ),
    ]
